import 'server-only';
import { mkdir, writeFile, unlink } from 'node:fs/promises';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';

/**
 * Flyers live in `data/uploads/`, next to the database, and are served by the
 * /media route rather than as static assets.
 *
 * They deliberately do not go in `public/`: Next.js resolves that directory
 * from a manifest built at build time, so anything uploaded afterwards is not
 * found. Keeping them beside the database also means one mounted volume covers
 * both on a host with an ephemeral filesystem.
 */
export const UPLOAD_DIR = join(process.cwd(), 'data', 'uploads');
export const UPLOAD_URL_PREFIX = '/media';

/** Filenames are generated by us; nothing else is allowed through. */
export const SAFE_NAME = /^[0-9]+-[0-9a-f]+\.(jpg|png|webp|gif)$/;

const MAX_BYTES = 8 * 1024 * 1024;

/** Only formats a browser will reliably render on the board. */
const ALLOWED: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
  'image/gif': 'gif',
};

export interface SavedUpload {
  file: string;
  width: number | null;
  height: number | null;
}

export async function saveFlyer(file: File): Promise<SavedUpload> {
  const ext = ALLOWED[file.type];
  if (!ext) {
    throw new Error('That file type is not supported. Use a JPG, PNG or WEBP image.');
  }
  if (file.size > MAX_BYTES) {
    throw new Error('That image is larger than 8MB. Please save it smaller and try again.');
  }

  const bytes = Buffer.from(await file.arrayBuffer());
  // The name is random rather than the uploaded filename, so nothing a person
  // types can escape the uploads directory or overwrite another flyer.
  const name = `${Date.now()}-${randomBytes(6).toString('hex')}.${ext}`;

  await mkdir(UPLOAD_DIR, { recursive: true });
  await writeFile(join(UPLOAD_DIR, name), bytes);

  const size = imageSize(bytes, file.type);
  return { file: name, width: size?.width ?? null, height: size?.height ?? null };
}

export async function deleteFlyer(name: string): Promise<void> {
  if (!SAFE_NAME.test(name)) return;
  try {
    await unlink(join(UPLOAD_DIR, name));
  } catch {
    // Already gone, which is the outcome we wanted anyway.
  }
}

export function flyerUrl(name: string | null | undefined): string | null {
  if (!name) return null;
  return `${UPLOAD_URL_PREFIX}/${name}`;
}

/**
 * Reads the pixel dimensions out of the file header. Knowing the aspect ratio
 * lets the board reserve the right shape before the image loads, so a portrait
 * flyer does not make the panel jump.
 */
function imageSize(buf: Buffer, mime: string): { width: number; height: number } | null {
  try {
    if (mime === 'image/png' && buf.length > 24) {
      return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
    }
    if (mime === 'image/gif' && buf.length > 10) {
      return { width: buf.readUInt16LE(6), height: buf.readUInt16LE(8) };
    }
    if (mime === 'image/jpeg') return jpegSize(buf);
    if (mime === 'image/webp') return webpSize(buf);
  } catch {
    // Dimensions are a nicety; the flyer still works without them.
  }
  return null;
}

function jpegSize(buf: Buffer): { width: number; height: number } | null {
  let i = 2; // skip SOI
  while (i < buf.length - 9) {
    if (buf[i] !== 0xff) { i++; continue; }
    const marker = buf[i + 1];
    // Start-of-frame markers carry the dimensions; skip the rest.
    if (marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker)) {
      return { height: buf.readUInt16BE(i + 5), width: buf.readUInt16BE(i + 7) };
    }
    i += 2 + buf.readUInt16BE(i + 2);
  }
  return null;
}

function webpSize(buf: Buffer): { width: number; height: number } | null {
  if (buf.length < 30 || buf.toString('ascii', 12, 16) !== 'VP8X') {
    if (buf.length > 30 && buf.toString('ascii', 12, 16) === 'VP8 ') {
      return { width: buf.readUInt16LE(26) & 0x3fff, height: buf.readUInt16LE(28) & 0x3fff };
    }
    return null;
  }
  return {
    width: 1 + (buf.readUIntLE(24, 3) & 0xffffff),
    height: 1 + (buf.readUIntLE(27, 3) & 0xffffff),
  };
}
